---
author: Dou
pubDatetime: 2022-09-23T15:22:00Z
modDatetime: 2023-12-21T09:12:47.400Z
title: 1.Promise.allSettled
slug: 1.Promise.allSettled
featured: true
draft: false
tags:
  - JavaScript
description:
  Some rules & recommendations for creating or adding new posts using AstroPaper
  theme.
---

```javascript
const promise1 = new Promise((resolve, reject) => {
  setTimeout(() => resolve(10), 500);
});
const promise2 = new Promise((resolve, reject) => {
  setTimeout(() => reject('Error'), 1000);
});

Promise.allSettled([promise1, promise2])
  .then(results => console.log(results))
  .catch(error => console.error(error));

```
在这段代码中，我们创建了两个 **Promise** 对象，分别是 **promise1** 和 **promise2**。每个 **Promise** 在一定的延迟后执行 **resolve** 或 **reject** 方法：

- **promise1** 在500毫秒后通过调用 **resolve(10)** 成功解决，并返回值 **10**。
- **promise2** 在1000毫秒后通过调用 **reject('Error')** 失败解决，并返回错误信息 **'Error'**。

接下来，使用 **Promise.allSettled()** 方法来处理这两个 **Promise**。**Promise.allSettled()** 接受一个 **Promise** 数组，并在所有给定的 **Promise** 完成后（不论成功或失败），返回一个新的 **Promise**，该 **Promise** 解析为一个对象数组，每个对象表示原始 **Promise** 的结果。<br />每个结果对象包含两个属性：

- **status**: 字符串，如果 **Promise** 成功解决则为 **'fulfilled'**，如果失败则为 **'rejected'**。
- **value** 或 **reason**: 如果 **Promise** 成功，**value** 属性会包含 **Promise** 的返回值；如果失败，**reason** 属性会包含拒绝的原因。

在这个例子中，**Promise.allSettled()** 最终会返回一个包含两个结果的数组：

- 第一个结果为 **{ status: 'fulfilled', value: 10 }**，表示 **promise1** 成功解决。
- 第二个结果为 **{ status: 'rejected', reason: 'Error' }**，表示 **promise2** 失败解决。

最后，通过 **.then()** 方法处理这个数组，打印到控制台。这段代码中不需要 **.catch()** 方法，因为 **Promise.allSettled()** 不会因任何 **Promise** 的拒绝而拒绝；它总是解决，无论包含的 **Promise** 是成功还是失败。
